TsumReached:
  asciigrids45:
  - crops/%s/2_GFDL-CM3_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MIROC5_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_45/TsumReached_1980-2010.asc.gz
  asciigrids85:
  - crops/%s/2_GFDL-CM3_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MIROC5_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_85/TsumReached_1980-2010.asc.gz
  asciigridhistorical:
  - crops/%s/historical/TsumReached_1980-2010.asc.gz
  outpath: crops/combined
  outputgridtempl: TsumReached_%s_%s.asc
  combinemode: 0
  threshold: -1
FrostOccurrence:
  asciigrids45:
  - crops/%s/2_GFDL-CM3_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MIROC5_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_45/FrostOccurrence_1980-2010.asc.gz
  asciigrids85:
  - crops/%s/2_GFDL-CM3_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MIROC5_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_85/FrostOccurrence_1980-2010.asc.gz
  asciigridhistorical: 
  - crops/%s/historical/FrostOccurrence_1980-2010.asc.gz
  outpath: crops/combined
  outputgridtempl: FrostOccurrence_%s_%s.asc
  combinemode: 0
  threshold: -1

TsumReachedNoFrost:
  asciigrids45:
  - crops/%s/2_GFDL-CM3_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_GFDL-CM3_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MIROC5_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MIROC5_45/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_45/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_45/FrostOccurrence_1980-2010.asc.gz
  asciigrids85:
  - crops/%s/2_GFDL-CM3_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_GFDL-CM3_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_GISS-E2-R_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_HadGEM2-ES_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MIROC5_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MIROC5_85/FrostOccurrence_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_85/TsumReached_1980-2010.asc.gz
  - crops/%s/2_MPI-ESM-MR_85/FrostOccurrence_1980-2010.asc.gz
  asciigridhistorical: 
  - crops/%s/historical/TsumReached_1980-2010.asc.gz
  - crops/%s/historical/FrostOccurrence_1980-2010.asc.gz
  outpath: crops/combined
  outputgridtempl: TsumReachedNoFrost_%s_%s.asc
  combinemode: 2
  threshold: 6
  defautmin: 0
